import type { Mountain } from "./types"

export const mountains: Mountain[] = [
  {
    id: "1",
    name: "高尾山",
    area: "東京都",
    level: "beginner",
    duration: "short",
    access: "train",
    season: "春・秋がおすすめ",
    description: "東京から電車で約1時間。ケーブルカーもあり、初心者に最適な山です。山頂からの富士山眺望が人気。",
    elevation: 599,
    tips: "混雑を避けるなら早朝がおすすめ",
    gear: "軽装でOK、スニーカーでも登れます",
    latitude: 35.6258,
  longitude: 139.2430,
  },
  {
    id: "2",
    name: "筑波山",
    area: "茨城県",
    level: "beginner",
    duration: "medium",
    access: "bus",
    season: "四季を通じて楽しめる",
    description: "関東平野を一望できる双峰の山。ロープウェイとケーブルカーがあり、体力に合わせてコースを選べます。",
    elevation: 877,
    tips: "女体山と男体山の両方を楽しめます",
    gear: "登山靴推奨、季節に応じた防寒具",
    latitude: 36.2256,
  longitude: 140.1067,
  },
  {
    id: "3",
    name: "大山",
    area: "神奈川県",
    level: "intermediate",
    duration: "medium",
    access: "bus",
    season: "紅葉シーズンが特に人気",
    description: "丹沢山系の東端に位置し、相模湾から富士山まで見渡せる眺望が魅力。登山道も整備されています。",
    elevation: 1252,
    tips: "大山阿夫利神社への参拝も楽しめます",
    gear: "登山靴必須、水分は多めに",
    latitude: 35.4406,
longitude: 139.2327,
  },
  {
    id: "4",
    name: "金時山",
    area: "神奈川県・静岡県",
    level: "intermediate",
    duration: "short",
    access: "car",
    season: "晴れた日の富士山ビューが最高",
    description: "箱根外輪山の最高峰。山頂からの富士山の眺めは絶景で、短時間で登れるのが魅力。",
    elevation: 1212,
    tips: "山頂の茶屋でまさかり担ぎ体験ができます",
    gear: "登山靴推奨、防寒着必須",
    latitude: 35.2896,
longitude: 139.0077,
  },
  {
    id: "5",
    name: "御岳山",
    area: "東京都",
    level: "beginner",
    duration: "short",
    access: "train",
    season: "レンゲショウマの咲く夏も人気",
    description: "武蔵御嶽神社を擁する霊山。ケーブルカーで山上まで行け、散策路も整備されています。",
    elevation: 929,
    tips: "宿坊に泊まって朝の神事に参加できます",
    gear: "軽装でOK、御師集落散策には歩きやすい靴を",
    latitude: 35.8019,
longitude: 139.1486,
  },
  {
    id: "6",
    name: "丹沢山",
    area: "神奈川県",
    level: "advanced",
    duration: "long",
    access: "bus",
    season: "春の新緑、秋の紅葉がおすすめ",
    description: "日本百名山の一つ。本格的な登山が楽しめ、尾根歩きの爽快感と達成感を味わえます。",
    elevation: 1567,
    tips: "塔ノ岳経由のコースが人気",
    gear: "本格登山装備必須、宿泊も検討を",
    latitude: 35.4865,
longitude: 139.1547,
  },
  {
    id: "7",
    name: "三頭山",
    area: "東京都",
    level: "intermediate",
    duration: "medium",
    access: "car",
    season: "ブナ林の新緑が美しい初夏",
    description: "奥多摩の名峰で、三つの頂を持つことから名付けられました。森林セラピーロードも整備されています。",
    elevation: 1531,
    tips: "都民の森から登るコースが人気",
    gear: "登山靴推奨、虫除けスプレーも",
    latitude: 35.7289,
longitude: 139.0394,
  },
  {
    id: "8",
    name: "陣馬山",
    area: "東京都・神奈川県",
    level: "beginner",
    duration: "medium",
    access: "train",
    season: "春の桜、秋の紅葉がおすすめ",
    description: "山頂の白馬像がシンボル。360度のパノラマビューと、茶屋での休憩が楽しめます。",
    elevation: 855,
    tips: "高尾山からの縦走コースも人気",
    gear: "スニーカーでも可、軽装で楽しめます",
    latitude: 35.6455,
longitude: 139.1895,
  },
  {
    id: "9",
    name: "雲取山",
    area: "東京都・埼玉県・山梨県",
    level: "advanced",
    duration: "long",
    access: "bus",
    season: "秋の紅葉、冬の雪景色も魅力",
    description: "東京都最高峰。本格的な山行が楽しめ、山小屋泊でゆっくり自然を満喫できます。",
    elevation: 2017,
    tips: "鴨沢からのコースが一般的",
    gear: "本格登山装備必須、山小屋予約を忘れずに",
    latitude: 35.8553,
longitude: 138.9437,
  },
  {
    id: "10",
    name: "鍋割山",
    area: "神奈川県",
    level: "intermediate",
    duration: "long",
    access: "bus",
    season: "通年楽しめるが、春秋がベスト",
    description: "山頂で食べる名物の鍋焼きうどんが大人気。達成感とグルメを同時に楽しめる山です。",
    elevation: 1273,
    tips: "鍋焼きうどんは午前中に着くのがおすすめ",
    gear: "登山靴必須、水を山頂まで運ぶボランティアも",
    latitude: 35.4513,
longitude: 139.1654,
  },
]
